//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Halley.CapaLogica.ServicioEnviarComprobanteFE {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentoElectronico", Namespace="http://schemas.datacontract.org/2004/07/OpenInvoicePeru.Comun.Dto.Modelos")]
    [System.SerializableAttribute()]
    public partial class DocumentoElectronico : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CalculoDetraccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CalculoIgvField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CalculoIscField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Halley.CapaLogica.ServicioEnviarComprobanteFE.DatoAdicional[] DatoAdicionalesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Halley.CapaLogica.ServicioEnviarComprobanteFE.DatosGuia DatosGuiaTransportistaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal DescuentoGlobalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Halley.CapaLogica.ServicioEnviarComprobanteFE.Discrepancia[] DiscrepanciasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocAnticipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Halley.CapaLogica.ServicioEnviarComprobanteFE.Contribuyente EmisorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ExoneradasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaEmisionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal GratuitasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal GravadasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal InafectasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Halley.CapaLogica.ServicioEnviarComprobanteFE.DetalleDocumento[] ItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MonedaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MonedaAnticipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MontoAnticipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MontoDetraccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MontoEnLetrasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MontoPercepcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlacaVehiculoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Halley.CapaLogica.ServicioEnviarComprobanteFE.Contribuyente ReceptorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Halley.CapaLogica.ServicioEnviarComprobanteFE.DocumentoRelacionado[] RelacionadosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RutaXMLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoDocAnticipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoOperacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalIgvField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalIscField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalOtrosTributosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalVentaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CalculoDetraccion {
            get {
                return this.CalculoDetraccionField;
            }
            set {
                if ((this.CalculoDetraccionField.Equals(value) != true)) {
                    this.CalculoDetraccionField = value;
                    this.RaisePropertyChanged("CalculoDetraccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CalculoIgv {
            get {
                return this.CalculoIgvField;
            }
            set {
                if ((this.CalculoIgvField.Equals(value) != true)) {
                    this.CalculoIgvField = value;
                    this.RaisePropertyChanged("CalculoIgv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CalculoIsc {
            get {
                return this.CalculoIscField;
            }
            set {
                if ((this.CalculoIscField.Equals(value) != true)) {
                    this.CalculoIscField = value;
                    this.RaisePropertyChanged("CalculoIsc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Halley.CapaLogica.ServicioEnviarComprobanteFE.DatoAdicional[] DatoAdicionales {
            get {
                return this.DatoAdicionalesField;
            }
            set {
                if ((object.ReferenceEquals(this.DatoAdicionalesField, value) != true)) {
                    this.DatoAdicionalesField = value;
                    this.RaisePropertyChanged("DatoAdicionales");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Halley.CapaLogica.ServicioEnviarComprobanteFE.DatosGuia DatosGuiaTransportista {
            get {
                return this.DatosGuiaTransportistaField;
            }
            set {
                if ((object.ReferenceEquals(this.DatosGuiaTransportistaField, value) != true)) {
                    this.DatosGuiaTransportistaField = value;
                    this.RaisePropertyChanged("DatosGuiaTransportista");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal DescuentoGlobal {
            get {
                return this.DescuentoGlobalField;
            }
            set {
                if ((this.DescuentoGlobalField.Equals(value) != true)) {
                    this.DescuentoGlobalField = value;
                    this.RaisePropertyChanged("DescuentoGlobal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Halley.CapaLogica.ServicioEnviarComprobanteFE.Discrepancia[] Discrepancias {
            get {
                return this.DiscrepanciasField;
            }
            set {
                if ((object.ReferenceEquals(this.DiscrepanciasField, value) != true)) {
                    this.DiscrepanciasField = value;
                    this.RaisePropertyChanged("Discrepancias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocAnticipo {
            get {
                return this.DocAnticipoField;
            }
            set {
                if ((object.ReferenceEquals(this.DocAnticipoField, value) != true)) {
                    this.DocAnticipoField = value;
                    this.RaisePropertyChanged("DocAnticipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Halley.CapaLogica.ServicioEnviarComprobanteFE.Contribuyente Emisor {
            get {
                return this.EmisorField;
            }
            set {
                if ((object.ReferenceEquals(this.EmisorField, value) != true)) {
                    this.EmisorField = value;
                    this.RaisePropertyChanged("Emisor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Exoneradas {
            get {
                return this.ExoneradasField;
            }
            set {
                if ((this.ExoneradasField.Equals(value) != true)) {
                    this.ExoneradasField = value;
                    this.RaisePropertyChanged("Exoneradas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaEmision {
            get {
                return this.FechaEmisionField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaEmisionField, value) != true)) {
                    this.FechaEmisionField = value;
                    this.RaisePropertyChanged("FechaEmision");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Gratuitas {
            get {
                return this.GratuitasField;
            }
            set {
                if ((this.GratuitasField.Equals(value) != true)) {
                    this.GratuitasField = value;
                    this.RaisePropertyChanged("Gratuitas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Gravadas {
            get {
                return this.GravadasField;
            }
            set {
                if ((this.GravadasField.Equals(value) != true)) {
                    this.GravadasField = value;
                    this.RaisePropertyChanged("Gravadas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdDocumento {
            get {
                return this.IdDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.IdDocumentoField, value) != true)) {
                    this.IdDocumentoField = value;
                    this.RaisePropertyChanged("IdDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Inafectas {
            get {
                return this.InafectasField;
            }
            set {
                if ((this.InafectasField.Equals(value) != true)) {
                    this.InafectasField = value;
                    this.RaisePropertyChanged("Inafectas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Halley.CapaLogica.ServicioEnviarComprobanteFE.DetalleDocumento[] Items {
            get {
                return this.ItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsField, value) != true)) {
                    this.ItemsField = value;
                    this.RaisePropertyChanged("Items");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Moneda {
            get {
                return this.MonedaField;
            }
            set {
                if ((object.ReferenceEquals(this.MonedaField, value) != true)) {
                    this.MonedaField = value;
                    this.RaisePropertyChanged("Moneda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MonedaAnticipo {
            get {
                return this.MonedaAnticipoField;
            }
            set {
                if ((object.ReferenceEquals(this.MonedaAnticipoField, value) != true)) {
                    this.MonedaAnticipoField = value;
                    this.RaisePropertyChanged("MonedaAnticipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MontoAnticipo {
            get {
                return this.MontoAnticipoField;
            }
            set {
                if ((this.MontoAnticipoField.Equals(value) != true)) {
                    this.MontoAnticipoField = value;
                    this.RaisePropertyChanged("MontoAnticipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MontoDetraccion {
            get {
                return this.MontoDetraccionField;
            }
            set {
                if ((this.MontoDetraccionField.Equals(value) != true)) {
                    this.MontoDetraccionField = value;
                    this.RaisePropertyChanged("MontoDetraccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MontoEnLetras {
            get {
                return this.MontoEnLetrasField;
            }
            set {
                if ((object.ReferenceEquals(this.MontoEnLetrasField, value) != true)) {
                    this.MontoEnLetrasField = value;
                    this.RaisePropertyChanged("MontoEnLetras");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MontoPercepcion {
            get {
                return this.MontoPercepcionField;
            }
            set {
                if ((this.MontoPercepcionField.Equals(value) != true)) {
                    this.MontoPercepcionField = value;
                    this.RaisePropertyChanged("MontoPercepcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlacaVehiculo {
            get {
                return this.PlacaVehiculoField;
            }
            set {
                if ((object.ReferenceEquals(this.PlacaVehiculoField, value) != true)) {
                    this.PlacaVehiculoField = value;
                    this.RaisePropertyChanged("PlacaVehiculo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Halley.CapaLogica.ServicioEnviarComprobanteFE.Contribuyente Receptor {
            get {
                return this.ReceptorField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceptorField, value) != true)) {
                    this.ReceptorField = value;
                    this.RaisePropertyChanged("Receptor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Halley.CapaLogica.ServicioEnviarComprobanteFE.DocumentoRelacionado[] Relacionados {
            get {
                return this.RelacionadosField;
            }
            set {
                if ((object.ReferenceEquals(this.RelacionadosField, value) != true)) {
                    this.RelacionadosField = value;
                    this.RaisePropertyChanged("Relacionados");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RutaXML {
            get {
                return this.RutaXMLField;
            }
            set {
                if ((object.ReferenceEquals(this.RutaXMLField, value) != true)) {
                    this.RutaXMLField = value;
                    this.RaisePropertyChanged("RutaXML");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoDocAnticipo {
            get {
                return this.TipoDocAnticipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoDocAnticipoField, value) != true)) {
                    this.TipoDocAnticipoField = value;
                    this.RaisePropertyChanged("TipoDocAnticipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoDocumento {
            get {
                return this.TipoDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoDocumentoField, value) != true)) {
                    this.TipoDocumentoField = value;
                    this.RaisePropertyChanged("TipoDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoOperacion {
            get {
                return this.TipoOperacionField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoOperacionField, value) != true)) {
                    this.TipoOperacionField = value;
                    this.RaisePropertyChanged("TipoOperacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalIgv {
            get {
                return this.TotalIgvField;
            }
            set {
                if ((this.TotalIgvField.Equals(value) != true)) {
                    this.TotalIgvField = value;
                    this.RaisePropertyChanged("TotalIgv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalIsc {
            get {
                return this.TotalIscField;
            }
            set {
                if ((this.TotalIscField.Equals(value) != true)) {
                    this.TotalIscField = value;
                    this.RaisePropertyChanged("TotalIsc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalOtrosTributos {
            get {
                return this.TotalOtrosTributosField;
            }
            set {
                if ((this.TotalOtrosTributosField.Equals(value) != true)) {
                    this.TotalOtrosTributosField = value;
                    this.RaisePropertyChanged("TotalOtrosTributos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalVenta {
            get {
                return this.TotalVentaField;
            }
            set {
                if ((this.TotalVentaField.Equals(value) != true)) {
                    this.TotalVentaField = value;
                    this.RaisePropertyChanged("TotalVenta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatosGuia", Namespace="http://schemas.datacontract.org/2004/07/OpenInvoicePeru.Comun.Dto.Modelos")]
    [System.SerializableAttribute()]
    public partial class DatosGuia : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoAutorizacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Halley.CapaLogica.ServicioEnviarComprobanteFE.Contribuyente DireccionDestinoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Halley.CapaLogica.ServicioEnviarComprobanteFE.Contribuyente DireccionOrigenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MarcaVehiculoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModoTransporteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreTransportistaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NroLicenciaConducirField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PesoBrutoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlacaVehiculoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RucTransportistaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoDocTransportistaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnidadMedidaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoAutorizacion {
            get {
                return this.CodigoAutorizacionField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoAutorizacionField, value) != true)) {
                    this.CodigoAutorizacionField = value;
                    this.RaisePropertyChanged("CodigoAutorizacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Halley.CapaLogica.ServicioEnviarComprobanteFE.Contribuyente DireccionDestino {
            get {
                return this.DireccionDestinoField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionDestinoField, value) != true)) {
                    this.DireccionDestinoField = value;
                    this.RaisePropertyChanged("DireccionDestino");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Halley.CapaLogica.ServicioEnviarComprobanteFE.Contribuyente DireccionOrigen {
            get {
                return this.DireccionOrigenField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionOrigenField, value) != true)) {
                    this.DireccionOrigenField = value;
                    this.RaisePropertyChanged("DireccionOrigen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MarcaVehiculo {
            get {
                return this.MarcaVehiculoField;
            }
            set {
                if ((object.ReferenceEquals(this.MarcaVehiculoField, value) != true)) {
                    this.MarcaVehiculoField = value;
                    this.RaisePropertyChanged("MarcaVehiculo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModoTransporte {
            get {
                return this.ModoTransporteField;
            }
            set {
                if ((object.ReferenceEquals(this.ModoTransporteField, value) != true)) {
                    this.ModoTransporteField = value;
                    this.RaisePropertyChanged("ModoTransporte");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreTransportista {
            get {
                return this.NombreTransportistaField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreTransportistaField, value) != true)) {
                    this.NombreTransportistaField = value;
                    this.RaisePropertyChanged("NombreTransportista");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NroLicenciaConducir {
            get {
                return this.NroLicenciaConducirField;
            }
            set {
                if ((object.ReferenceEquals(this.NroLicenciaConducirField, value) != true)) {
                    this.NroLicenciaConducirField = value;
                    this.RaisePropertyChanged("NroLicenciaConducir");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PesoBruto {
            get {
                return this.PesoBrutoField;
            }
            set {
                if ((this.PesoBrutoField.Equals(value) != true)) {
                    this.PesoBrutoField = value;
                    this.RaisePropertyChanged("PesoBruto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlacaVehiculo {
            get {
                return this.PlacaVehiculoField;
            }
            set {
                if ((object.ReferenceEquals(this.PlacaVehiculoField, value) != true)) {
                    this.PlacaVehiculoField = value;
                    this.RaisePropertyChanged("PlacaVehiculo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RucTransportista {
            get {
                return this.RucTransportistaField;
            }
            set {
                if ((object.ReferenceEquals(this.RucTransportistaField, value) != true)) {
                    this.RucTransportistaField = value;
                    this.RaisePropertyChanged("RucTransportista");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoDocTransportista {
            get {
                return this.TipoDocTransportistaField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoDocTransportistaField, value) != true)) {
                    this.TipoDocTransportistaField = value;
                    this.RaisePropertyChanged("TipoDocTransportista");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnidadMedida {
            get {
                return this.UnidadMedidaField;
            }
            set {
                if ((object.ReferenceEquals(this.UnidadMedidaField, value) != true)) {
                    this.UnidadMedidaField = value;
                    this.RaisePropertyChanged("UnidadMedida");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Contribuyente", Namespace="http://schemas.datacontract.org/2004/07/OpenInvoicePeru.Comun.Dto.Modelos")]
    [System.SerializableAttribute()]
    public partial class Contribuyente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistritoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreComercialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreLegalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NroDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProvinciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UbigeoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrbanizacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Departamento {
            get {
                return this.DepartamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartamentoField, value) != true)) {
                    this.DepartamentoField = value;
                    this.RaisePropertyChanged("Departamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Distrito {
            get {
                return this.DistritoField;
            }
            set {
                if ((object.ReferenceEquals(this.DistritoField, value) != true)) {
                    this.DistritoField = value;
                    this.RaisePropertyChanged("Distrito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreComercial {
            get {
                return this.NombreComercialField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreComercialField, value) != true)) {
                    this.NombreComercialField = value;
                    this.RaisePropertyChanged("NombreComercial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreLegal {
            get {
                return this.NombreLegalField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreLegalField, value) != true)) {
                    this.NombreLegalField = value;
                    this.RaisePropertyChanged("NombreLegal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NroDocumento {
            get {
                return this.NroDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.NroDocumentoField, value) != true)) {
                    this.NroDocumentoField = value;
                    this.RaisePropertyChanged("NroDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Provincia {
            get {
                return this.ProvinciaField;
            }
            set {
                if ((object.ReferenceEquals(this.ProvinciaField, value) != true)) {
                    this.ProvinciaField = value;
                    this.RaisePropertyChanged("Provincia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoDocumento {
            get {
                return this.TipoDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoDocumentoField, value) != true)) {
                    this.TipoDocumentoField = value;
                    this.RaisePropertyChanged("TipoDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ubigeo {
            get {
                return this.UbigeoField;
            }
            set {
                if ((object.ReferenceEquals(this.UbigeoField, value) != true)) {
                    this.UbigeoField = value;
                    this.RaisePropertyChanged("Ubigeo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Urbanizacion {
            get {
                return this.UrbanizacionField;
            }
            set {
                if ((object.ReferenceEquals(this.UrbanizacionField, value) != true)) {
                    this.UrbanizacionField = value;
                    this.RaisePropertyChanged("Urbanizacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatoAdicional", Namespace="http://schemas.datacontract.org/2004/07/OpenInvoicePeru.Comun.Dto.Modelos")]
    [System.SerializableAttribute()]
    public partial class DatoAdicional : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContenidoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contenido {
            get {
                return this.ContenidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ContenidoField, value) != true)) {
                    this.ContenidoField = value;
                    this.RaisePropertyChanged("Contenido");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Discrepancia", Namespace="http://schemas.datacontract.org/2004/07/OpenInvoicePeru.Comun.Dto.Modelos")]
    [System.SerializableAttribute()]
    public partial class Discrepancia : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NroReferenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NroReferencia {
            get {
                return this.NroReferenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.NroReferenciaField, value) != true)) {
                    this.NroReferenciaField = value;
                    this.RaisePropertyChanged("NroReferencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetalleDocumento", Namespace="http://schemas.datacontract.org/2004/07/OpenInvoicePeru.Comun.Dto.Modelos")]
    [System.SerializableAttribute()]
    public partial class DetalleDocumento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoItemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal DescuentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ImpuestoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ImpuestoSelectivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal OtroImpuestoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PrecioReferencialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PrecioUnitarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SumaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoImpuestoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoPrecioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalVentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnidadMedidaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoItem {
            get {
                return this.CodigoItemField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoItemField, value) != true)) {
                    this.CodigoItemField = value;
                    this.RaisePropertyChanged("CodigoItem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Descuento {
            get {
                return this.DescuentoField;
            }
            set {
                if ((this.DescuentoField.Equals(value) != true)) {
                    this.DescuentoField = value;
                    this.RaisePropertyChanged("Descuento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Impuesto {
            get {
                return this.ImpuestoField;
            }
            set {
                if ((this.ImpuestoField.Equals(value) != true)) {
                    this.ImpuestoField = value;
                    this.RaisePropertyChanged("Impuesto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ImpuestoSelectivo {
            get {
                return this.ImpuestoSelectivoField;
            }
            set {
                if ((this.ImpuestoSelectivoField.Equals(value) != true)) {
                    this.ImpuestoSelectivoField = value;
                    this.RaisePropertyChanged("ImpuestoSelectivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal OtroImpuesto {
            get {
                return this.OtroImpuestoField;
            }
            set {
                if ((this.OtroImpuestoField.Equals(value) != true)) {
                    this.OtroImpuestoField = value;
                    this.RaisePropertyChanged("OtroImpuesto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PrecioReferencial {
            get {
                return this.PrecioReferencialField;
            }
            set {
                if ((this.PrecioReferencialField.Equals(value) != true)) {
                    this.PrecioReferencialField = value;
                    this.RaisePropertyChanged("PrecioReferencial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PrecioUnitario {
            get {
                return this.PrecioUnitarioField;
            }
            set {
                if ((this.PrecioUnitarioField.Equals(value) != true)) {
                    this.PrecioUnitarioField = value;
                    this.RaisePropertyChanged("PrecioUnitario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Suma {
            get {
                return this.SumaField;
            }
            set {
                if ((this.SumaField.Equals(value) != true)) {
                    this.SumaField = value;
                    this.RaisePropertyChanged("Suma");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoImpuesto {
            get {
                return this.TipoImpuestoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoImpuestoField, value) != true)) {
                    this.TipoImpuestoField = value;
                    this.RaisePropertyChanged("TipoImpuesto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoPrecio {
            get {
                return this.TipoPrecioField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoPrecioField, value) != true)) {
                    this.TipoPrecioField = value;
                    this.RaisePropertyChanged("TipoPrecio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalVenta {
            get {
                return this.TotalVentaField;
            }
            set {
                if ((this.TotalVentaField.Equals(value) != true)) {
                    this.TotalVentaField = value;
                    this.RaisePropertyChanged("TotalVenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnidadMedida {
            get {
                return this.UnidadMedidaField;
            }
            set {
                if ((object.ReferenceEquals(this.UnidadMedidaField, value) != true)) {
                    this.UnidadMedidaField = value;
                    this.RaisePropertyChanged("UnidadMedida");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentoRelacionado", Namespace="http://schemas.datacontract.org/2004/07/OpenInvoicePeru.Comun.Dto.Modelos")]
    [System.SerializableAttribute()]
    public partial class DocumentoRelacionado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NroDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoDocumentoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NroDocumento {
            get {
                return this.NroDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.NroDocumentoField, value) != true)) {
                    this.NroDocumentoField = value;
                    this.RaisePropertyChanged("NroDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoDocumento {
            get {
                return this.TipoDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoDocumentoField, value) != true)) {
                    this.TipoDocumentoField = value;
                    this.RaisePropertyChanged("TipoDocumento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaComun", Namespace="http://schemas.datacontract.org/2004/07/OpenInvoicePeru.Comun.Dto.Intercambio")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Halley.CapaLogica.ServicioEnviarComprobanteFE.RespuestaComunConArchivo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Halley.CapaLogica.ServicioEnviarComprobanteFE.EnviarDocumentoResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Halley.CapaLogica.ServicioEnviarComprobanteFE.DocumentoResponse))]
    public partial class RespuestaComun : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ExitoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PilaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Exito {
            get {
                return this.ExitoField;
            }
            set {
                if ((this.ExitoField.Equals(value) != true)) {
                    this.ExitoField = value;
                    this.RaisePropertyChanged("Exito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeError {
            get {
                return this.MensajeErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeErrorField, value) != true)) {
                    this.MensajeErrorField = value;
                    this.RaisePropertyChanged("MensajeError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pila {
            get {
                return this.PilaField;
            }
            set {
                if ((object.ReferenceEquals(this.PilaField, value) != true)) {
                    this.PilaField = value;
                    this.RaisePropertyChanged("Pila");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaComunConArchivo", Namespace="http://schemas.datacontract.org/2004/07/OpenInvoicePeru.Comun.Dto.Intercambio")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Halley.CapaLogica.ServicioEnviarComprobanteFE.EnviarDocumentoResponse))]
    public partial class RespuestaComunConArchivo : Halley.CapaLogica.ServicioEnviarComprobanteFE.RespuestaComun {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreArchivoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreArchivo {
            get {
                return this.NombreArchivoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreArchivoField, value) != true)) {
                    this.NombreArchivoField = value;
                    this.RaisePropertyChanged("NombreArchivo");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnviarDocumentoResponse", Namespace="http://schemas.datacontract.org/2004/07/OpenInvoicePeru.Comun.Dto.Intercambio")]
    [System.SerializableAttribute()]
    public partial class EnviarDocumentoResponse : Halley.CapaLogica.ServicioEnviarComprobanteFE.RespuestaComunConArchivo {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoRespuestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeRespuestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TramaZipCdrField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoRespuesta {
            get {
                return this.CodigoRespuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoRespuestaField, value) != true)) {
                    this.CodigoRespuestaField = value;
                    this.RaisePropertyChanged("CodigoRespuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeRespuesta {
            get {
                return this.MensajeRespuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeRespuestaField, value) != true)) {
                    this.MensajeRespuestaField = value;
                    this.RaisePropertyChanged("MensajeRespuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TramaZipCdr {
            get {
                return this.TramaZipCdrField;
            }
            set {
                if ((object.ReferenceEquals(this.TramaZipCdrField, value) != true)) {
                    this.TramaZipCdrField = value;
                    this.RaisePropertyChanged("TramaZipCdr");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentoResponse", Namespace="http://schemas.datacontract.org/2004/07/OpenInvoicePeru.Comun.Dto.Intercambio")]
    [System.SerializableAttribute()]
    public partial class DocumentoResponse : Halley.CapaLogica.ServicioEnviarComprobanteFE.RespuestaComun {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RutaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TramaXmlSinFirmaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ruta {
            get {
                return this.RutaField;
            }
            set {
                if ((object.ReferenceEquals(this.RutaField, value) != true)) {
                    this.RutaField = value;
                    this.RaisePropertyChanged("Ruta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TramaXmlSinFirma {
            get {
                return this.TramaXmlSinFirmaField;
            }
            set {
                if ((object.ReferenceEquals(this.TramaXmlSinFirmaField, value) != true)) {
                    this.TramaXmlSinFirmaField = value;
                    this.RaisePropertyChanged("TramaXmlSinFirma");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentoResumen", Namespace="http://schemas.datacontract.org/2004/07/OpenInvoicePeru.Comun.Dto.Modelos")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Halley.CapaLogica.ServicioEnviarComprobanteFE.ResumenDiarioNuevo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Halley.CapaLogica.ServicioEnviarComprobanteFE.ComunicacionBaja))]
    public partial class DocumentoResumen : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Halley.CapaLogica.ServicioEnviarComprobanteFE.Contribuyente EmisorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaEmisionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaReferenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdDocumentoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Halley.CapaLogica.ServicioEnviarComprobanteFE.Contribuyente Emisor {
            get {
                return this.EmisorField;
            }
            set {
                if ((object.ReferenceEquals(this.EmisorField, value) != true)) {
                    this.EmisorField = value;
                    this.RaisePropertyChanged("Emisor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaEmision {
            get {
                return this.FechaEmisionField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaEmisionField, value) != true)) {
                    this.FechaEmisionField = value;
                    this.RaisePropertyChanged("FechaEmision");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaReferencia {
            get {
                return this.FechaReferenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaReferenciaField, value) != true)) {
                    this.FechaReferenciaField = value;
                    this.RaisePropertyChanged("FechaReferencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdDocumento {
            get {
                return this.IdDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.IdDocumentoField, value) != true)) {
                    this.IdDocumentoField = value;
                    this.RaisePropertyChanged("IdDocumento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResumenDiarioNuevo", Namespace="http://schemas.datacontract.org/2004/07/OpenInvoicePeru.Comun.Dto.Modelos")]
    [System.SerializableAttribute()]
    public partial class ResumenDiarioNuevo : Halley.CapaLogica.ServicioEnviarComprobanteFE.DocumentoResumen {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Halley.CapaLogica.ServicioEnviarComprobanteFE.GrupoResumenNuevo[] ResumenesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RutaXMLField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Halley.CapaLogica.ServicioEnviarComprobanteFE.GrupoResumenNuevo[] Resumenes {
            get {
                return this.ResumenesField;
            }
            set {
                if ((object.ReferenceEquals(this.ResumenesField, value) != true)) {
                    this.ResumenesField = value;
                    this.RaisePropertyChanged("Resumenes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RutaXML {
            get {
                return this.RutaXMLField;
            }
            set {
                if ((object.ReferenceEquals(this.RutaXMLField, value) != true)) {
                    this.RutaXMLField = value;
                    this.RaisePropertyChanged("RutaXML");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ComunicacionBaja", Namespace="http://schemas.datacontract.org/2004/07/OpenInvoicePeru.Comun.Dto.Modelos")]
    [System.SerializableAttribute()]
    public partial class ComunicacionBaja : Halley.CapaLogica.ServicioEnviarComprobanteFE.DocumentoResumen {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Halley.CapaLogica.ServicioEnviarComprobanteFE.DocumentoBaja[] BajasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RutaXMLField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Halley.CapaLogica.ServicioEnviarComprobanteFE.DocumentoBaja[] Bajas {
            get {
                return this.BajasField;
            }
            set {
                if ((object.ReferenceEquals(this.BajasField, value) != true)) {
                    this.BajasField = value;
                    this.RaisePropertyChanged("Bajas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RutaXML {
            get {
                return this.RutaXMLField;
            }
            set {
                if ((object.ReferenceEquals(this.RutaXMLField, value) != true)) {
                    this.RutaXMLField = value;
                    this.RaisePropertyChanged("RutaXML");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentoBaja", Namespace="http://schemas.datacontract.org/2004/07/OpenInvoicePeru.Comun.Dto.Modelos")]
    [System.SerializableAttribute()]
    public partial class DocumentoBaja : Halley.CapaLogica.ServicioEnviarComprobanteFE.DocumentoResumenDetalle {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorrelativoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MotivoBajaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correlativo {
            get {
                return this.CorrelativoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorrelativoField, value) != true)) {
                    this.CorrelativoField = value;
                    this.RaisePropertyChanged("Correlativo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MotivoBaja {
            get {
                return this.MotivoBajaField;
            }
            set {
                if ((object.ReferenceEquals(this.MotivoBajaField, value) != true)) {
                    this.MotivoBajaField = value;
                    this.RaisePropertyChanged("MotivoBaja");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GrupoResumenNuevo", Namespace="http://schemas.datacontract.org/2004/07/OpenInvoicePeru.Comun.Dto.Modelos")]
    [System.SerializableAttribute()]
    public partial class GrupoResumenNuevo : Halley.CapaLogica.ServicioEnviarComprobanteFE.GrupoResumen {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoEstadoItemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentoRelacionadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NroDocumentoReceptorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoDocumentoReceptorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoDocumentoRelacionadoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoEstadoItem {
            get {
                return this.CodigoEstadoItemField;
            }
            set {
                if ((this.CodigoEstadoItemField.Equals(value) != true)) {
                    this.CodigoEstadoItemField = value;
                    this.RaisePropertyChanged("CodigoEstadoItem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentoRelacionado {
            get {
                return this.DocumentoRelacionadoField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentoRelacionadoField, value) != true)) {
                    this.DocumentoRelacionadoField = value;
                    this.RaisePropertyChanged("DocumentoRelacionado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdDocumento {
            get {
                return this.IdDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.IdDocumentoField, value) != true)) {
                    this.IdDocumentoField = value;
                    this.RaisePropertyChanged("IdDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NroDocumentoReceptor {
            get {
                return this.NroDocumentoReceptorField;
            }
            set {
                if ((object.ReferenceEquals(this.NroDocumentoReceptorField, value) != true)) {
                    this.NroDocumentoReceptorField = value;
                    this.RaisePropertyChanged("NroDocumentoReceptor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoDocumentoReceptor {
            get {
                return this.TipoDocumentoReceptorField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoDocumentoReceptorField, value) != true)) {
                    this.TipoDocumentoReceptorField = value;
                    this.RaisePropertyChanged("TipoDocumentoReceptor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoDocumentoRelacionado {
            get {
                return this.TipoDocumentoRelacionadoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoDocumentoRelacionadoField, value) != true)) {
                    this.TipoDocumentoRelacionadoField = value;
                    this.RaisePropertyChanged("TipoDocumentoRelacionado");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentoResumenDetalle", Namespace="http://schemas.datacontract.org/2004/07/OpenInvoicePeru.Comun.Dto.Modelos")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Halley.CapaLogica.ServicioEnviarComprobanteFE.DocumentoBaja))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Halley.CapaLogica.ServicioEnviarComprobanteFE.GrupoResumen))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Halley.CapaLogica.ServicioEnviarComprobanteFE.GrupoResumenNuevo))]
    public partial class DocumentoResumenDetalle : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SerieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoDocumentoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Serie {
            get {
                return this.SerieField;
            }
            set {
                if ((object.ReferenceEquals(this.SerieField, value) != true)) {
                    this.SerieField = value;
                    this.RaisePropertyChanged("Serie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoDocumento {
            get {
                return this.TipoDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoDocumentoField, value) != true)) {
                    this.TipoDocumentoField = value;
                    this.RaisePropertyChanged("TipoDocumento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GrupoResumen", Namespace="http://schemas.datacontract.org/2004/07/OpenInvoicePeru.Comun.Dto.Modelos")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Halley.CapaLogica.ServicioEnviarComprobanteFE.GrupoResumenNuevo))]
    public partial class GrupoResumen : Halley.CapaLogica.ServicioEnviarComprobanteFE.DocumentoResumenDetalle {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CorrelativoFinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CorrelativoInicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ExoneradasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ExportacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal GratuitasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal GravadasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal InafectasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MonedaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalDescuentosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalIgvField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalIscField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalOtrosImpuestosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalVentaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CorrelativoFin {
            get {
                return this.CorrelativoFinField;
            }
            set {
                if ((this.CorrelativoFinField.Equals(value) != true)) {
                    this.CorrelativoFinField = value;
                    this.RaisePropertyChanged("CorrelativoFin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CorrelativoInicio {
            get {
                return this.CorrelativoInicioField;
            }
            set {
                if ((this.CorrelativoInicioField.Equals(value) != true)) {
                    this.CorrelativoInicioField = value;
                    this.RaisePropertyChanged("CorrelativoInicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Exoneradas {
            get {
                return this.ExoneradasField;
            }
            set {
                if ((this.ExoneradasField.Equals(value) != true)) {
                    this.ExoneradasField = value;
                    this.RaisePropertyChanged("Exoneradas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Exportacion {
            get {
                return this.ExportacionField;
            }
            set {
                if ((this.ExportacionField.Equals(value) != true)) {
                    this.ExportacionField = value;
                    this.RaisePropertyChanged("Exportacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Gratuitas {
            get {
                return this.GratuitasField;
            }
            set {
                if ((this.GratuitasField.Equals(value) != true)) {
                    this.GratuitasField = value;
                    this.RaisePropertyChanged("Gratuitas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Gravadas {
            get {
                return this.GravadasField;
            }
            set {
                if ((this.GravadasField.Equals(value) != true)) {
                    this.GravadasField = value;
                    this.RaisePropertyChanged("Gravadas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Inafectas {
            get {
                return this.InafectasField;
            }
            set {
                if ((this.InafectasField.Equals(value) != true)) {
                    this.InafectasField = value;
                    this.RaisePropertyChanged("Inafectas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Moneda {
            get {
                return this.MonedaField;
            }
            set {
                if ((object.ReferenceEquals(this.MonedaField, value) != true)) {
                    this.MonedaField = value;
                    this.RaisePropertyChanged("Moneda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalDescuentos {
            get {
                return this.TotalDescuentosField;
            }
            set {
                if ((this.TotalDescuentosField.Equals(value) != true)) {
                    this.TotalDescuentosField = value;
                    this.RaisePropertyChanged("TotalDescuentos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalIgv {
            get {
                return this.TotalIgvField;
            }
            set {
                if ((this.TotalIgvField.Equals(value) != true)) {
                    this.TotalIgvField = value;
                    this.RaisePropertyChanged("TotalIgv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalIsc {
            get {
                return this.TotalIscField;
            }
            set {
                if ((this.TotalIscField.Equals(value) != true)) {
                    this.TotalIscField = value;
                    this.RaisePropertyChanged("TotalIsc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalOtrosImpuestos {
            get {
                return this.TotalOtrosImpuestosField;
            }
            set {
                if ((this.TotalOtrosImpuestosField.Equals(value) != true)) {
                    this.TotalOtrosImpuestosField = value;
                    this.RaisePropertyChanged("TotalOtrosImpuestos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalVenta {
            get {
                return this.TotalVentaField;
            }
            set {
                if ((this.TotalVentaField.Equals(value) != true)) {
                    this.TotalVentaField = value;
                    this.RaisePropertyChanged("TotalVenta");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaComunConArchivo2", Namespace="http://schemas.datacontract.org/2004/07/WCF_FE")]
    [System.SerializableAttribute()]
    public partial class RespuestaComunConArchivo2 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoRespuestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ExitoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeRespuestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreArchivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NroTicketField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PilaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TramaZipCdrField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoRespuesta {
            get {
                return this.CodigoRespuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoRespuestaField, value) != true)) {
                    this.CodigoRespuestaField = value;
                    this.RaisePropertyChanged("CodigoRespuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Exito {
            get {
                return this.ExitoField;
            }
            set {
                if ((this.ExitoField.Equals(value) != true)) {
                    this.ExitoField = value;
                    this.RaisePropertyChanged("Exito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeError {
            get {
                return this.MensajeErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeErrorField, value) != true)) {
                    this.MensajeErrorField = value;
                    this.RaisePropertyChanged("MensajeError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeRespuesta {
            get {
                return this.MensajeRespuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeRespuestaField, value) != true)) {
                    this.MensajeRespuestaField = value;
                    this.RaisePropertyChanged("MensajeRespuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreArchivo {
            get {
                return this.NombreArchivoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreArchivoField, value) != true)) {
                    this.NombreArchivoField = value;
                    this.RaisePropertyChanged("NombreArchivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NroTicket {
            get {
                return this.NroTicketField;
            }
            set {
                if ((object.ReferenceEquals(this.NroTicketField, value) != true)) {
                    this.NroTicketField = value;
                    this.RaisePropertyChanged("NroTicket");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pila {
            get {
                return this.PilaField;
            }
            set {
                if ((object.ReferenceEquals(this.PilaField, value) != true)) {
                    this.PilaField = value;
                    this.RaisePropertyChanged("Pila");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TramaZipCdr {
            get {
                return this.TramaZipCdrField;
            }
            set {
                if ((object.ReferenceEquals(this.TramaZipCdrField, value) != true)) {
                    this.TramaZipCdrField = value;
                    this.RaisePropertyChanged("TramaZipCdr");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioEnviarComprobanteFE.IFEService")]
    public interface IFEService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFEService/GenerarXMLFactura", ReplyAction="http://tempuri.org/IFEService/GenerarXMLFacturaResponse")]
        Halley.CapaLogica.ServicioEnviarComprobanteFE.DocumentoResponse GenerarXMLFactura(Halley.CapaLogica.ServicioEnviarComprobanteFE.DocumentoElectronico _documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFEService/GenerarXMLBaja", ReplyAction="http://tempuri.org/IFEService/GenerarXMLBajaResponse")]
        Halley.CapaLogica.ServicioEnviarComprobanteFE.DocumentoResponse GenerarXMLBaja(Halley.CapaLogica.ServicioEnviarComprobanteFE.ComunicacionBaja _documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFEService/GenerarXMLResumenDiario", ReplyAction="http://tempuri.org/IFEService/GenerarXMLResumenDiarioResponse")]
        Halley.CapaLogica.ServicioEnviarComprobanteFE.DocumentoResponse GenerarXMLResumenDiario(Halley.CapaLogica.ServicioEnviarComprobanteFE.ResumenDiarioNuevo _documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFEService/EnviarSunat", ReplyAction="http://tempuri.org/IFEService/EnviarSunatResponse")]
        Halley.CapaLogica.ServicioEnviarComprobanteFE.RespuestaComunConArchivo2 EnviarSunat(string TipoDocumento, string RutaXml, string RutaCdr, string RutaCertificado, string ClaveCertificado, string RucEmisor, string UsuarioSol, string ClaveSol, string Correlativo, string RutaWSSunat, bool EsResumen);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFEService/EnviarXML", ReplyAction="http://tempuri.org/IFEService/EnviarXMLResponse")]
        Halley.CapaLogica.ServicioEnviarComprobanteFE.RespuestaComunConArchivo2 EnviarXML(string RutaWS, string usuario, string clave, string RucEmisor, string TipoDocumento, string IdentificadorArchivo, bool EsResumen, string CarpetaXML, string CarpetaCdr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFEService/ObtenerTicket", ReplyAction="http://tempuri.org/IFEService/ObtenerTicketResponse")]
        Halley.CapaLogica.ServicioEnviarComprobanteFE.EnviarDocumentoResponse ObtenerTicket(string RutaWS, string usuario, string clave, string RucEmisor, string NroTicket, string IdentificadorArchivo, string CarpetaCdr);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFEServiceChannel : Halley.CapaLogica.ServicioEnviarComprobanteFE.IFEService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FEServiceClient : System.ServiceModel.ClientBase<Halley.CapaLogica.ServicioEnviarComprobanteFE.IFEService>, Halley.CapaLogica.ServicioEnviarComprobanteFE.IFEService {
        
        public FEServiceClient() {
        }
        
        public FEServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FEServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FEServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FEServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Halley.CapaLogica.ServicioEnviarComprobanteFE.DocumentoResponse GenerarXMLFactura(Halley.CapaLogica.ServicioEnviarComprobanteFE.DocumentoElectronico _documento) {
            return base.Channel.GenerarXMLFactura(_documento);
        }
        
        public Halley.CapaLogica.ServicioEnviarComprobanteFE.DocumentoResponse GenerarXMLBaja(Halley.CapaLogica.ServicioEnviarComprobanteFE.ComunicacionBaja _documento) {
            return base.Channel.GenerarXMLBaja(_documento);
        }
        
        public Halley.CapaLogica.ServicioEnviarComprobanteFE.DocumentoResponse GenerarXMLResumenDiario(Halley.CapaLogica.ServicioEnviarComprobanteFE.ResumenDiarioNuevo _documento) {
            return base.Channel.GenerarXMLResumenDiario(_documento);
        }
        
        public Halley.CapaLogica.ServicioEnviarComprobanteFE.RespuestaComunConArchivo2 EnviarSunat(string TipoDocumento, string RutaXml, string RutaCdr, string RutaCertificado, string ClaveCertificado, string RucEmisor, string UsuarioSol, string ClaveSol, string Correlativo, string RutaWSSunat, bool EsResumen) {
            return base.Channel.EnviarSunat(TipoDocumento, RutaXml, RutaCdr, RutaCertificado, ClaveCertificado, RucEmisor, UsuarioSol, ClaveSol, Correlativo, RutaWSSunat, EsResumen);
        }
        
        public Halley.CapaLogica.ServicioEnviarComprobanteFE.RespuestaComunConArchivo2 EnviarXML(string RutaWS, string usuario, string clave, string RucEmisor, string TipoDocumento, string IdentificadorArchivo, bool EsResumen, string CarpetaXML, string CarpetaCdr) {
            return base.Channel.EnviarXML(RutaWS, usuario, clave, RucEmisor, TipoDocumento, IdentificadorArchivo, EsResumen, CarpetaXML, CarpetaCdr);
        }
        
        public Halley.CapaLogica.ServicioEnviarComprobanteFE.EnviarDocumentoResponse ObtenerTicket(string RutaWS, string usuario, string clave, string RucEmisor, string NroTicket, string IdentificadorArchivo, string CarpetaCdr) {
            return base.Channel.ObtenerTicket(RutaWS, usuario, clave, RucEmisor, NroTicket, IdentificadorArchivo, CarpetaCdr);
        }
    }
}
